[package]
name = "virtual_list_demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wxdragon = { path = "../../../rust/wxdragon", default-features = false }

[build-dependencies]
embed-manifest = "1.4"
