[package]
name = "simple_stc_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wxdragon = { path = "../../../rust/wxdragon", features = ["stc"] }

[build-dependencies]
embed-manifest = "1.4"
