//! Generates C shim functions from the `.wxd` spec files in `cpp/spec`.
//!
//! Most of the shim is mechanical: cast the handle, check it for null, convert the
//! arguments, call one wxWidgets method and convert the result. The spec files describe
//! those functions and this module writes their declarations (`wxd_generated.h`, included
//! by `wxdragon.h` and so seen by bindgen) and definitions (one `.cpp` per spec file, built
//! by CMake). Anything that is not mechanical stays hand-written in `cpp/src`.
//!
//! # Spec format
//!
//! ```text
//! include wx/checkbox.h                  # extra header for the generated .cpp
//!
//! class CheckBox : wxCheckBox            # handle wxd_CheckBox_t, wraps wxCheckBox
//!     create(Window parent, Id id, string label, Point pos, Size size, Style style)
//!     bool IsChecked()                    # wxd_CheckBox_IsChecked(wxd_CheckBox_t* self)
//!     string GetLabel() const             # const self, returned through a buffer
//!     int GetValue() = -1                 # value returned for a null handle
//!     void Foo(int a) => self->Bar(a * 2) # custom call expression
//! ```
//!
//! Parameter types:
//! - `int`, `bool`, `double`, `Id`, `Style`, ... are passed through unchanged.
//! - `string` is a `const char*` converted with `wxString::FromUTF8` (null reads as "").
//! - `string? name = EXPR` falls back to the C++ expression `EXPR` when null.
//! - `Point` and `Size` are `wxd_Point`/`wxd_Size` converted to `wxPoint`/`wxSize`.
//! - `Window` is a `wxd_Window_t*` handle; a null handle makes the function return early.
//!
//! Return types are the pass-through types, `void`, `Point`, `Size` and `string`. A
//! `string` return becomes an `int` result plus trailing `char* buffer, size_t buffer_len`
//! parameters, filled by `wxd_cpp_utils::copy_wxstring_to_buffer` (-1 for a null handle).
//!
//! In a `=> EXPR` override, `self` is the typed wxWidgets pointer and each parameter name
//! refers to its converted value. For `create`, `EXPR` is the `new` expression.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

type Result<T> = std::result::Result<T, String>;

/// Generates the shim from every `.wxd` file in `spec_dir` into `out_dir/include` and
/// `out_dir/src`. Files are only rewritten when their content changes.
pub fn generate(spec_dir: &Path, out_dir: &Path) -> Result<()> {
    let mut specs: Vec<PathBuf> = fs::read_dir(spec_dir)
        .map_err(|e| format!("{}: {e}", spec_dir.display()))?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|ext| ext == "wxd"))
        .collect();
    specs.sort();

    let include_dir = out_dir.join("include");
    let src_dir = out_dir.join("src");
    fs::create_dir_all(&include_dir).map_err(|e| e.to_string())?;
    fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;

    let mut header = String::from(
        "// Generated by wxdragon-sys/shimgen.rs from cpp/spec/*.wxd. Do not edit.\n\
         // Included by wxdragon.h inside its extern \"C\" block.\n\
         #ifndef WXD_GENERATED_H\n#define WXD_GENERATED_H\n",
    );
    let mut expected_sources = Vec::new();

    for path in &specs {
        let text = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
        let spec = parse(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let stem = path.file_stem().unwrap().to_string_lossy();
        let (decls, source) = emit(&spec, &format!("{stem}.wxd"))?;
        header.push_str(&decls);
        let name = format!("{stem}.cpp");
        write_if_changed(&src_dir.join(&name), &source)?;
        expected_sources.push(name);
    }

    header.push_str("\n#endif // WXD_GENERATED_H\n");
    write_if_changed(&include_dir.join("wxd_generated.h"), &header)?;

    // Remove sources whose spec file was deleted so CMake does not keep building them.
    for entry in fs::read_dir(&src_dir).map_err(|e| e.to_string())?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if !expected_sources.contains(&name) {
            let _ = fs::remove_file(entry.path());
        }
    }
    Ok(())
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if fs::read_to_string(path).is_ok_and(|old| old == content) {
        return Ok(());
    }
    fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))
}

// --- Spec model -------------------------------------------------------------

struct Spec {
    includes: Vec<String>,
    classes: Vec<Class>,
}

struct Class {
    /// Name used in `wxd_<name>_t` and `wxd_<name>_<Method>`.
    name: String,
    /// The wxWidgets class the handle points to.
    wx_class: String,
    funcs: Vec<Func>,
}

struct Func {
    /// `None` for `create`.
    ret: Option<Type>,
    name: String,
    params: Vec<Param>,
    is_const: bool,
    null_default: Option<String>,
    call: Option<String>,
}

struct Param {
    ty: Type,
    name: String,
    /// For `string?`: the C++ expression used when the argument is null.
    fallback: Option<String>,
}

#[derive(Clone, PartialEq)]
enum Type {
    Void,
    /// A C type passed through unchanged, e.g. `int` or `wxd_Id`.
    Plain(String),
    String,
    OptString,
    Point,
    Size,
    /// A handle to another wrapped object: (`wxd_X_t` name, wxWidgets class).
    Handle(String, String),
}

fn parse_type(word: &str) -> Result<Type> {
    let plain = |c: &str| Ok(Type::Plain(c.to_string()));
    match word {
        "void" => Ok(Type::Void),
        "bool" | "int" | "double" | "size_t" | "int32_t" | "int64_t" | "uint32_t" | "uint64_t" => plain(word),
        "unsigned" => plain("unsigned int"),
        "long" => plain("wxd_Long_t"),
        "Id" => plain("wxd_Id"),
        "Style" => plain("wxd_Style_t"),
        "string" => Ok(Type::String),
        "string?" => Ok(Type::OptString),
        "Point" => Ok(Type::Point),
        "Size" => Ok(Type::Size),
        "Window" => Ok(Type::Handle("Window".into(), "wxWindow".into())),
        _ => Err(format!("unknown type `{word}`")),
    }
}

impl Type {
    /// The C type used in the declaration.
    fn c_type(&self) -> String {
        match self {
            Type::Void => "void".into(),
            Type::Plain(c) => c.clone(),
            Type::String | Type::OptString => "const char*".into(),
            Type::Point => "wxd_Point".into(),
            Type::Size => "wxd_Size".into(),
            Type::Handle(name, _) => format!("wxd_{name}_t*"),
        }
    }

    /// The value returned for a null handle when the spec does not give one.
    fn null_default(&self) -> Option<&'static str> {
        match self {
            Type::Void => None,
            Type::Plain(c) if c == "bool" => Some("false"),
            Type::Plain(_) => Some("0"),
            Type::String => Some("-1"),
            Type::Point => Some("wxd_Point{0, 0}"),
            Type::Size => Some("wxd_Size{0, 0}"),
            Type::Handle(..) => Some("nullptr"),
            Type::OptString => None,
        }
    }
}

fn parse(text: &str) -> Result<Spec> {
    let mut spec = Spec {
        includes: Vec::new(),
        classes: Vec::new(),
    };
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.split(" #").next().unwrap().trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let err = |msg: String| format!("line {}: {msg}", lineno + 1);
        if let Some(rest) = line.strip_prefix("include ") {
            spec.includes.push(rest.trim().to_string());
        } else if let Some(rest) = line.strip_prefix("class ") {
            let Some((name, wx_class)) = rest.split_once(':') else {
                return Err(err("expected `class <Name> : <wxClass>`".into()));
            };
            let (name, wx_class) = (name.trim(), wx_class.trim());
            if name.is_empty() || wx_class.is_empty() || wx_class.contains(char::is_whitespace) {
                return Err(err("expected `class <Name> : <wxClass>`".into()));
            }
            spec.classes.push(Class {
                name: name.into(),
                wx_class: wx_class.into(),
                funcs: Vec::new(),
            });
        } else {
            let class = spec
                .classes
                .last_mut()
                .ok_or_else(|| err("function outside a class".into()))?;
            class.funcs.push(parse_func(line).map_err(err)?);
        }
    }
    Ok(spec)
}

fn parse_func(line: &str) -> Result<Func> {
    let (decl, call) = match line.split_once("=>") {
        Some((d, c)) => (d.trim(), Some(c.trim().to_string())),
        None => (line, None),
    };
    let open = decl.find('(').ok_or("missing `(`")?;
    let close = decl.rfind(')').ok_or("missing `)`")?;
    let head: Vec<&str> = decl[..open].split_whitespace().collect();
    let (ret, name) = match head[..] {
        ["create"] => (None, "Create".to_string()),
        [ret, name] => (Some(parse_type(ret)?), name.to_string()),
        _ => {
            return Err(format!(
                "expected `<ret> <Name>(...)` or `create(...)`, got `{}`",
                &decl[..open]
            ));
        }
    };

    let mut params = Vec::new();
    for p in decl[open + 1..close].split(',').map(str::trim).filter(|p| !p.is_empty()) {
        let (p, fallback) = match p.split_once('=') {
            Some((p, f)) => (p.trim(), Some(f.trim().to_string())),
            None => (p, None),
        };
        let [ty, pname] = p.split_whitespace().collect::<Vec<_>>()[..] else {
            return Err(format!("bad parameter `{p}`"));
        };
        let ty = parse_type(ty)?;
        if fallback.is_some() != (ty == Type::OptString) {
            return Err(format!("only `string?` parameters take a `= fallback`: `{p}`"));
        }
        params.push(Param {
            ty,
            name: pname.to_string(),
            fallback,
        });
    }

    let mut tail = decl[close + 1..].trim();
    let is_const = tail.starts_with("const");
    if is_const {
        tail = tail["const".len()..].trim();
    }
    let null_default = match tail.strip_prefix('=') {
        Some(d) => Some(d.trim().to_string()),
        None if tail.is_empty() => None,
        None => return Err(format!("unexpected `{tail}`")),
    };
    Ok(Func {
        ret,
        name,
        params,
        is_const,
        null_default,
        call,
    })
}

// --- Emission ---------------------------------------------------------------

fn emit(spec: &Spec, spec_name: &str) -> Result<(String, String)> {
    let mut decls = format!("\n// --- {spec_name} ---\n");
    let mut src = format!("// Generated by wxdragon-sys/shimgen.rs from cpp/spec/{spec_name}. Do not edit.\n");
    src.push_str("#include <wx/wxprec.h>\n#include <wx/wx.h>\n");
    for inc in &spec.includes {
        writeln!(src, "#include <{inc}>").unwrap();
    }
    src.push_str("#include \"wxdragon.h\"\n#include \"wxd_utils.h\"\n\nextern \"C\" {\n");

    for class in &spec.classes {
        for f in &class.funcs {
            let (decl_params, def_params) = signature(class, f);
            let c_ret = match &f.ret {
                None => format!("wxd_{}_t*", class.name),
                Some(Type::String) => "int".to_string(),
                Some(t) => t.c_type(),
            };
            let c_name = format!("wxd_{}_{}", class.name, f.name);
            writeln!(decls, "WXD_EXPORTED {c_ret}\n{c_name}({});", decl_params.join(", ")).unwrap();
            write!(src, "\nWXD_EXPORTED {c_ret}\n{c_name}({})\n{{\n", def_params.join(", ")).unwrap();
            src.push_str(&body(class, f)?);
            src.push_str("}\n");
        }
    }
    src.push_str("\n} // extern \"C\"\n");
    Ok((decls, src))
}

/// Parameter lists for the declaration and the definition. The definition renames the
/// parameters that need converting (`label` -> `label_in`) so the converted locals can take
/// the spec names, which is what a `=> EXPR` override refers to.
fn signature(class: &Class, f: &Func) -> (Vec<String>, Vec<String>) {
    let mut decl = Vec::new();
    let mut def = Vec::new();
    if f.ret.is_some() {
        let constness = if f.is_const { "const " } else { "" };
        decl.push(format!("{constness}wxd_{}_t* self", class.name));
        def.push(format!("{constness}wxd_{}_t* self_in", class.name));
    }
    for p in &f.params {
        let c = p.ty.c_type();
        decl.push(format!("{c} {}", p.name));
        let suffix = if matches!(p.ty, Type::Plain(_)) { "" } else { "_in" };
        def.push(format!("{c} {}{suffix}", p.name));
    }
    if f.ret == Some(Type::String) {
        for list in [&mut decl, &mut def] {
            list.push("char* buffer".into());
            list.push("size_t buffer_len".into());
        }
    }
    (decl, def)
}

fn body(class: &Class, f: &Func) -> Result<String> {
    let mut out = String::new();
    let default = match &f.null_default {
        Some(d) => Some(d.as_str()),
        None => match &f.ret {
            None => Some("nullptr"),
            Some(t) => t.null_default(),
        },
    };
    let early_return = match default {
        Some(d) => format!("return {d};"),
        None => "return;".to_string(),
    };

    // Null checks for the handle and every required handle parameter.
    let mut checks = Vec::new();
    if f.ret.is_some() {
        checks.push("!self_in".to_string());
    }
    for p in &f.params {
        if matches!(p.ty, Type::Handle(..)) {
            checks.push(format!("!{}_in", p.name));
        }
    }
    if !checks.is_empty() {
        writeln!(out, "    if ({})\n        {early_return}", checks.join(" || ")).unwrap();
    }

    if f.ret.is_some() {
        let constness = if f.is_const { "const " } else { "" };
        writeln!(
            out,
            "    {constness}{wx}* self = reinterpret_cast<{constness}{wx}*>(self_in);",
            wx = class.wx_class
        )
        .unwrap();
    }
    for p in &f.params {
        let n = &p.name;
        let conv = match &p.ty {
            Type::Plain(_) | Type::Void => continue,
            Type::String => format!("wxString {n} = wxString::FromUTF8({n}_in ? {n}_in : \"\");"),
            Type::OptString => format!(
                "wxString {n} = {n}_in ? wxString::FromUTF8({n}_in) : wxString({});",
                p.fallback.as_deref().unwrap()
            ),
            Type::Point => format!("wxPoint {n}({n}_in.x, {n}_in.y);"),
            Type::Size => format!("wxSize {n}({n}_in.width, {n}_in.height);"),
            Type::Handle(_, wx) => format!("{wx}* {n} = reinterpret_cast<{wx}*>({n}_in);"),
        };
        writeln!(out, "    {conv}").unwrap();
    }

    let args = f.params.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(", ");
    let call = match (&f.call, &f.ret) {
        (Some(c), _) => c.clone(),
        (None, None) => format!("new {}({args})", class.wx_class),
        (None, Some(_)) => format!("self->{}({args})", f.name),
    };
    let stmt = match &f.ret {
        None => format!("return reinterpret_cast<wxd_{}_t*>({call});", class.name),
        Some(Type::Void) => format!("{call};"),
        Some(Type::Plain(_)) => format!("return {call};"),
        Some(Type::String) => {
            format!("return static_cast<int>(wxd_cpp_utils::copy_wxstring_to_buffer({call}, buffer, buffer_len));")
        }
        Some(Type::Point) => format!("wxPoint result = {call};\n    return wxd_Point{{result.x, result.y}};"),
        Some(Type::Size) => format!("wxSize result = {call};\n    return wxd_Size{{result.GetWidth(), result.GetHeight()}};"),
        Some(Type::Handle(..)) | Some(Type::OptString) => {
            return Err(format!("{}: unsupported return type", f.name));
        }
    };
    writeln!(out, "    {stmt}").unwrap();
    Ok(out)
}
