[package]
name = "simplebook_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wxdragon = { path = "../../../rust/wxdragon", features = ["xrc"] }
wxdragon-macros = { path = "../../../rust/wxdragon-macros" }