[package]
name = "tokio_async_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
wxdragon = { path = "../../../rust/wxdragon" }
tokio = { version = "1.0", features = ["full"] }

[[bin]]
name = "tokio_async_demo"
path = "src/main.rs" 