[package]
name = "tokio_async_demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tokio_async_demo"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
wxdragon = { path = "../../../rust/wxdragon" }
