[package]
name = "dnd_advanced"
version = "0.1.0"
authors = ["wxDragon Contributors"]
edition = "2024"
publish = false

[dependencies]
wxdragon = { path = "../../../rust/wxdragon" }

[build-dependencies]
embed-manifest = "1.4"
