[package]
name = "simple_xrc_test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
wxdragon = { path = "../../../rust/wxdragon", features = ["xrc"] } 

[build-dependencies]
embed-manifest = "1.4"
