[package]
name = "simple_xrc_test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
env_logger = "0.11.8"
log = "0.4"
wxdragon = { path = "../../../rust/wxdragon", features = ["xrc"] } 

[build-dependencies]
embed-manifest = "1.4"
