[package]
name = "custom_widget"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
paste = "1.0"
wxdragon = { path = "../../../rust/wxdragon" }

[build-dependencies]
embed-manifest = "1.4"
