[package]
name = "window_features_test"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
wxdragon = { path = "../../../rust/wxdragon" }

[build-dependencies]
embed-manifest = "1.4"
embed-resource = "3.0.6"
serde_json = "1"
