[package]
name = "minimal_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
# Depend on the safe wrapper crate now
wxdragon = { path = "../../../rust/wxdragon" }
image = { version = "0.25.1", default-features = false, features = ["png"] }